// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwN4QlwHnXENbyQS-oxx9ZWuGClqA31r4',
    appId: '1:449165816010:web:24ff5cf8e5e57261c50433',
    messagingSenderId: '449165816010',
    projectId: 'flutter-project-96234',
    authDomain: 'flutter-project-96234.firebaseapp.com',
    storageBucket: 'flutter-project-96234.appspot.com',
    measurementId: 'G-DPJGYRZ3F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwoqO6xuxcM8Y1vk2U42eYvpy9yfSn3xM',
    appId: '1:449165816010:android:e69959b7845a9372c50433',
    messagingSenderId: '449165816010',
    projectId: 'flutter-project-96234',
    storageBucket: 'flutter-project-96234.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBULScHFid89YpjKfHgWbbTrpt1GnIM-TI',
    appId: '1:449165816010:ios:ee542feda13f18b5c50433',
    messagingSenderId: '449165816010',
    projectId: 'flutter-project-96234',
    storageBucket: 'flutter-project-96234.appspot.com',
    iosClientId: '449165816010-3g6svmepba6ar89t43ddjr4trsc7fh64.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorAppointment',
  );
}
